#ifndef COMMANDS_H
#define COMMANDS_H

const char* commands[] = {
    "Request PGN",
    "Proprietary A",
    "Transfer PGN",
    "Acknowledgement",
    "Request 2 PGN",
    "Transfer Protocol - Connection Abort",
    "Transport Protocol - Connection Management",
    "Transport Protocol - Data Transfer",
    "BAM - Broadcast Announce Message",
    "CON - Connection Mode",
    "RTS - Request to Send",
    "CTS - Clear to Send",
    "EOM - End of Message",
    "Abort",
    "Address Delete",
    "Address Requested",
    "Request for PGN",
    "Response to Request PGN",
    "Address Claimed",
    "Commanded Address",
    "Address Claimed by Another Device",
    "Proprietary B",
    "Aftertreatment 1 Diesel Exhaust Fluid Tank 1 Information",
    "Electronic Brake Controller 1",
    "Electronic Brake Controller 2",
    "Electronic Engine Controller 2",
    "Electronic Engine Controller 1",
    "Electronic Transmission Controller 1",
    "Electronic Transmission Controller 2",
    "Electronic Axle Controller 1",
    "Electronic Retarder Controller 1",
    "Hydraulic Pressure Controller",
    "Electronic Tractor Controller",
    "Implement Controller",
    "Ground-Based Speed Sensor",
    "Virtual Terminal",
    "Vehicle Position",
    "Vehicle Direction and Speed",
    "Vehicle Dynamics",
    "Adaptive Cruise Control",
    "Lighting Command",
    "Lighting Data",
    "Hitch Control Command",
    "Hitch Control Data",
    "PTO Control Command",
    "PTO Control Data",
    "Auxiliary Valve Command",
    "Auxiliary Valve Data",
    "Engine Configuration",
    "Engine Fluid Level/Pressure",
    "Engine Torque History",
    "Engine Speed History",
    "Shutdown",
    "Idle Operation",
    "Fan Drive",
    "Cab Illumination",
    "Steering Controller",
    "Vehicle Weight",
    "Ambient Conditions",
    "Vehicle Electrical Power",
    "Inlet/Exhaust Conditions",
    "Turbocharger",
    "Exhaust Gas Recirculation",
    "Fuel Economy",
    "Vehicle Hours",
    "Total Vehicle Distance",
    "Total Engine Hours",
    "Total Engine Revolutions",
    "Total Fuel Used",
    "Total Idle Fuel Used",
    "Total Idle Hours",
    "Vehicle Identification",
    "Trip Information",
    "Trip Fuel Economy",
    "Trip Distance",
    "Trip Time",
    "Trip Idle Time",
    "Trip PTO Time",
    "Trip Engine Hours",
    "Trip Fuel Used",
    "Trip Idle Fuel Used",
    "Trip Distance on Battery",
    "Trip Fuel Used on Battery",
    "Trip Time on Battery",
    "Trip Distance on Alternative Fuel",
    "Trip Fuel Used on Alternative Fuel",
    "Trip Time on Alternative Fuel",
    "Trip Distance on Natural Gas",
    "Trip Fuel Used on Natural Gas",
    "Trip Time on Natural Gas",
    "Engine Protection System",
    "Engine Protection System Timer",
    "Engine Protection System Configuration",
    "Engine Protection System Status",
    "Engine Protection System History",
    "Engine Protection System Configuration 2",
    "Engine Protection System Status 2",
    "Engine Protection System History 2",
    "Aftertreatment 1 Diesel Particulate Filter",
    "Aftertreatment 1 Diesel Exhaust Fluid Tank 2 Information",
    "Aftertreatment 2 Diesel Particulate Filter",
    "Aftertreatment 2 Diesel Exhaust Fluid Tank 1 Information",
    "Aftertreatment 1 Gas Intake",
    "Aftertreatment 1 Gas Outlet",
    "Aftertreatment 2 Gas Intake",
    "Aftertreatment 2 Gas Outlet",
    "Aftertreatment 1 SCR Information",
    "Aftertreatment 2 SCR Information",
    "Aftertreatment 1 Diesel Particulate Filter Regeneration",
    "Aftertreatment 2 Diesel Particulate Filter Regeneration",
    "Aftertreatment 1 Diesel Exhaust Fluid Tank 3 Information",
    "Aftertreatment 1 Diesel Exhaust Fluid Tank 4 Information",
    "Aftertreatment 2 Diesel Exhaust Fluid Tank 2 Information",
    "Aftertreatment 2 Diesel Exhaust Fluid Tank 3 Information",
    "Aftertreatment 2 Diesel Exhaust Fluid Tank 4 Information",
    "Aftertreatment 1 Diesel Particulate Filter History",
    "Aftertreatment 2 Diesel Particulate Filter History",
    "Aftertreatment 1 Diesel Particulate Filter Control",
    "Aftertreatment 2 Diesel Particulate Filter Control",
    "Aftertreatment 1 Diesel Exhaust Fluid Tank 1 Control",
    "Aftertreatment 1 Diesel Exhaust Fluid Tank 2 Control",
    "Aftertreatment 2 Diesel Exhaust Fluid Tank 1 Control",
    "Aftertreatment 2 Diesel Exhaust Fluid Tank 2 Control",
    "Aftertreatment 1 Gas Particulate Filter",
    "Aftertreatment 2 Gas Particulate Filter",
    "Aftertreatment 1 Gas Particulate Filter Regeneration",
    "Aftertreatment 2 Gas Particulate Filter Regeneration",
    "Aftertreatment 1 Gas Particulate Filter History",
    "Aftertreatment 2 Gas Particulate Filter History",
    "Aftertreatment 1 Gas Particulate Filter Control",
    "Aftertreatment 2 Gas Particulate Filter Control",
    "Engine Fuel Delivery Pressure",
    "Engine Oil Information",
    "Engine Coolant Information",
    "Engine Air Intake Information",
    "Engine Exhaust Information",
    "Engine Power Information",
    "Engine Load Information",
    "Engine Timing Information",
    "Engine Combustion Information",
    "Engine Emission Control Information",
    "Engine Diagnostic Information",
    "Engine Maintenance Information",
    "Engine Performance Information",
    "Engine Calibration Information",
    "Engine Configuration 2",
    "Engine Configuration 3",
    "Engine Configuration 4",
    "Engine Configuration 5",
    "Engine Configuration 6",
    "Engine Configuration 7",
    "Engine Configuration 8",
    "Engine Configuration 9",
    "Engine Configuration 10",
    "Engine Configuration 11",
    "Engine Configuration 12",
    "Engine Configuration 13",
    "Engine Configuration 14",
    "Engine Configuration 15",
    "Engine Configuration 16",
    "Engine Configuration 17",
    "Engine Configuration 18",
    "Engine Configuration 19",
    "Engine Configuration 20",
    "Service Component Identification",
    "Service Distance Information",
    "Service Time Information",
    "Service Component Status",
    "Service Component Configuration",
    "Service Component History",
    "Service Component Calibration",
    "Service Component Performance",
    "Service Component Diagnostics",
    "Service Component Maintenance",
    "Service Component Operation",
    "Service Component Faults",
    "Service Component Warnings",
    "Service Component Alarms",
    "Service Component Events",
    "Service Component Logs",
    "Vehicle Network Information",
    "Vehicle Network Status",
    "Vehicle Network Configuration",
    "Vehicle Network Performance",
    "Vehicle Network Diagnostics",
    "Vehicle Network Maintenance",
    "Vehicle Network Operation",
    "Vehicle Network Faults",
    "Vehicle Network Warnings",
    "Vehicle Network Alarms",
    "Vehicle Network Events",
    "Vehicle Network Logs",
    "Vehicle Network Security",
    "Vehicle Network Access",
    "Vehicle Network Control",
    "Vehicle Network Monitoring",
    "Vehicle Network Reporting",
    "Vehicle Network Analysis",
    "Vehicle Network Optimization",
    "Vehicle Network Integration",
    "Vehicle Network Compatibility",
    "Vehicle Network Reliability",
    "Vehicle Network Availability",
    "Vehicle Network Scalability",
    "Vehicle Network Flexibility",
    "Vehicle Network Adaptability",
    "Software Identification",
    "ECU Identification",
    "ECU Performance",
    "Engine Hours/Revolutions",
    "Time/Date",
    "Vehicle Distance",
    "Fuel Consumption",
    "Vehicle Speed",
    "Trip Fan Information",
    "Trip Fuel Information",
    "Trip Engine Information",
    "Trip Transmission Information",
    "Trip Brake Information",
    "Trip Suspension Information",
    "Trip Axle Information",
    "Trip Steering Information",
    "Trip Cruise Control Information",
    "Trip Driver Information",
    "Trip Vehicle Information",
    "Trip Environmental Information",
    "Trip Electrical Information",
    "Trip Diagnostic Information",
    "Trip Aftertreatment Information",
    "Trip Battery Information",
    "Trip Alternative Fuel Information",
    "Trip Natural Gas Information",
    "DM4 - Freeze Frame Parameters",
    "DM5 - Diagnostic Readiness 1",
    "DM6 - Pending Diagnostic Trouble Codes",
    "DM7 - Commanded Diagnostic Test",
    "DM8 - Diagnostic Data Clear/Reset for Active DTCs",
    "DM9 - Diagnostic Data Clear/Reset for Previously Active DTCs",
    "DM1 - Active Diagnostic Trouble Codes",
    "DM2 - Previously Active Diagnostic Trouble Codes",
    "DM3 - Diagnostic Data Clear/Reset",
    "DM11 - Clear All Active and Previously Active DTCs",
    "DM12 - Emissions-Related Active Diagnostic Trouble Codes",
    "DM13 - Stop/Start Broadcast",
    "DM14 - Memory Access Request",
    "DM15 - Memory Access Response",
    "DM16 - Binary Data Transfer",
    "DM17 - Diagnostic Readiness 2",
    "DM18 - Boot Load Data",
    "DM19 - Calibration Information",
    "DM20 - Monitor Performance Ratio",
    "DM21 - Diagnostic Readiness 3",
    "DM22 - Individual Clear/Reset of Active DTCs",
    "DM23 - Previously Active Emissions-Related DTCs",
    "DM24 - SPN Support",
    "DM25 - Expanded Freeze Frame",
    "DM26 - Diagnostic Readiness 4",
    "DM27 - All Pending DTCs",
    "DM28 - Permanent DTCs",
    "DM29 - DTC Counts",
    "DM30 - Scaled Test Results",
    "DM31 - DTC to Lamp Association",
    "DM32 - Test Results for Specific Monitored Systems",
    "DM33 - Emission Increasing Auxiliary Emission Control Device Active Time",
    "DM34 - Normalized Trigger Engine Operation Data",
    "DM35 - Engine Operation Tracking Data",
    "DM36 - Engine Operation Tracking Data 2",
    "DM37 - Engine Operation Tracking Data 3",
    "DM38 - Engine Operation Tracking Data 4",
    "DM39 - Engine Operation Tracking Data 5",
    "DM40 - Engine Operation Tracking Data 6",
    "DM41 - Engine Operation Tracking Data 7",
    "DM42 - Engine Operation Tracking Data 8",
    "DM43 - Engine Operation Tracking Data 9",
    "DM44 - Engine Operation Tracking Data 10",
    "DM45 - Engine Operation Tracking Data 11",
    "Transmission Configuration",
    "Transmission Oil Information",
    "Transmission Clutch Information",
    "Transmission Torque Converter Information",
    "Transmission Shift Information",
    "Transmission Diagnostic Information",
    "Transmission Maintenance Information",
    "Transmission Performance Information",
    "Transmission Calibration Information",
    "Axle Information",
    "Axle Configuration",
    "Axle Diagnostic Information",
    "Axle Maintenance Information",
    "Brake Information",
    "Brake Configuration",
    "Brake Diagnostic Information",
    "Brake Maintenance Information",
    "Suspension Information",
    "Suspension Configuration",
    "Suspension Diagnostic Information",
    "Suspension Maintenance Information",
    "Vehicle Body Information",
    "Vehicle Body Configuration",
    "Vehicle Body Diagnostic Information",
    "Vehicle Body Maintenance Information",
    "Cab Information",
    "Cab Configuration",
    "Cab Diagnostic Information",
    "Cab Maintenance Information",
    "Trailer Information",
    "Trailer Configuration",
    "Trailer Diagnostic Information",
    "Trailer Maintenance Information",
    "Tire Information",
    "Tire Configuration",
    "Tire Diagnostic Information",
    "Tire Maintenance Information",
    "Wheel Information",
    "Wheel Configuration",
    "Wheel Diagnostic Information",
    "Wheel Maintenance Information",
    "Steering Information",
    "Steering Configuration",
    "Steering Diagnostic Information",
    "Steering Maintenance Information",
    "Hitch Information",
    "Hitch Configuration",
    "Hitch Diagnostic Information",
    "Hitch Maintenance Information",
    "PTO Information",
    "PTO Configuration",
    "PTO Diagnostic Information",
    "PTO Maintenance Information",
    "Auxiliary Power Unit Information",
    "Auxiliary Power Unit Configuration",
    "Auxiliary Power Unit Diagnostic Information",
    "Auxiliary Power Unit Maintenance Information",
    "Battery Information",
    "Battery Configuration",
    "Battery Diagnostic Information",
    "Battery Maintenance Information",
    "Alternator Information",
    "Alternator Configuration",
    "Alternator Diagnostic Information",
    "Alternator Maintenance Information",
    "Starter Information",
    "Starter Configuration",
    "Starter Diagnostic Information",
    "Starter Maintenance Information",
    "Hybrid System Information",
    "Hybrid System Configuration",
    "Hybrid System Diagnostic Information",
    "Hybrid System Maintenance Information",
    "Electric Vehicle Information",
    "Electric Vehicle Configuration",
    "Electric Vehicle Diagnostic Information",
    "Electric Vehicle Maintenance Information",
    "Fuel Cell Information",
    "Fuel Cell Configuration",
    "Fuel Cell Diagnostic Information",
    "Fuel Cell Maintenance Information",
    "Engine Cooling System Information",
    "Engine Cooling System Configuration",
    "Engine Cooling System Diagnostic Information",
    "Engine Cooling System Maintenance Information",
    "Exhaust System Information",
    "Exhaust System Configuration",
    "Exhaust System Diagnostic Information",
    "Exhaust System Maintenance Information",
    "Intake System Information",
    "Intake System Configuration",
    "Intake System Diagnostic Information",
    "Intake System Maintenance Information",
    "Fuel System Information",
    "Fuel System Configuration",
    "Fuel System Diagnostic Information",
    "Fuel System Maintenance Information",
    "Hydraulic System Information",
    "Hydraulic System Configuration",
    "Hydraulic System Diagnostic Information",
    "Hydraulic System Maintenance Information",
    "Pneumatic System Information",
    "Pneumatic System Configuration",
    "Pneumatic System Diagnostic Information",
    "Pneumatic System Maintenance Information",
    "Climate Control Information",
    "Climate Control Configuration",
    "Climate Control Diagnostic Information",
    "Climate Control Maintenance Information",
    "Lighting System Information",
    "Lighting System Configuration",
    "Lighting System Diagnostic Information",
    "Lighting System Maintenance Information",
    "Driver Assistance System Information",
    "Driver Assistance System Configuration",
    "Driver Assistance System Diagnostic Information",
    "Driver Assistance System Maintenance Information",
    "Navigation System Information",
    "Navigation System Configuration",
    "Navigation System Diagnostic Information",
    "Navigation System Maintenance Information",
    "Telematics System Information",
    "Telematics System Configuration",
    "Telematics System Diagnostic Information",
    "Telematics System Maintenance Information",
    "Infotainment System Information",
    "Infotainment System Configuration",
    "Infotainment System Diagnostic Information",
    "Infotainment System Maintenance Information",
    "Security System Information",
    "Security System Configuration",
    "Security System Diagnostic Information",
    "Security System Maintenance Information",
    "Communication System Information",
    "Communication System Configuration",
    "Communication System Diagnostic Information",
    "Communication System Maintenance Information",
    "Operator Interface Information",
    "Operator Interface Configuration",
    "Operator Interface Diagnostic Information",
    "Operator Interface Maintenance Information",
    "Environmental Control Information",
    "Environmental Control Configuration",
    "Environmental Control Diagnostic Information",
    "Environmental Control Maintenance Information",
    "CCVS - Cruise Control/Vehicle Speed",
    "LFE - Fuel Economy Liquid",
    "AMB - Ambient Conditions",
    "IC1 - Intake/Exhaust Conditions 1",
    "VD - Vehicle Distance",
    "HRW - High Resolution Wheel Speed",
    "EFL/P1 - Engine Fluid Level/Pressure 1",
    "TF - Transmission Fluids",
    "AI - Air Inlet",
    "VI - Vehicle Identification",
    "FD - Fan Drive",
    "DD - Dash Display",
    "AWSS - Auxiliary Water Pump and Speed Sensors",
    "AWS - Auxiliary Water Pump Speed",
    "WFI - Water Fuel Information",
};

#endif // COMMANDS_H
