const char* meanings[] = {
    "Block Erase (32KB)",
    "Block Erase (64KB)",
    "Chip Erase",
    "Dual Output Fast Read",
    "Enter 4-Byte Address Mode",
    "Exit 4-Byte Address Mode",
    "Fast Read",
    "Flush FIFO",
    "Get AGC Damping Factor",
    "Get AGC Enable State",
    "Get AGC Histogram Statistics",
    "Get AGC Policy",
    "Get AGC ROI",
    "Get Camera Status",
    "Get FFC Status",
    "Get FIFO length",
    "Get GPIO Mode",
    "Get Operation Mode",
    "Get Sys Ping",
    "Page Program",
    "Power-down",
    "Quad I/O Fast Read",
    "Quad Output Fast Read",
    "Quad Page Program",
    "Read DEFVALA (Default Value A)",
    "Read DEFVALB (Default Value B)",
    "Read Data",
    "Read FIFO",
    "Read GPINTENA (Interrupt Enable A)",
    "Read GPINTENB (Interrupt Enable B)",
    "Read GPIOA (Port A Value)",
    "Read GPIOB (Port B Value)",
    "Read GPPUA (Pull-up Resistor A)",
    "Read GPPUB (Pull-up Resistor B)",
    "Read INTCAPA (Captured Value A)",
    "Read INTCAPB (Captured Value B)",
    "Read INTCONA (Interrupt Control A)",
    "Read INTCONB (Interrupt Control B)",
    "Read INTFA (Interrupt Flag A)",
    "Read INTFB (Interrupt Flag B)",
    "Read IOCON (Configuration Register)",
    "Read IODIRA (Direction Register A)",
    "Read IODIRB (Direction Register B)",
    "Read IPOLA (Input Polarity A)",
    "Read IPOLB (Input Polarity B)",
    "Read JEDEC ID",
    "Read Manufacturer/Device ID",
    "Read Status Register-1",
    "Read Status Register-2",
    "Read Status Register-3",
    "Read register 0xFF",
    "Release Power-down / ID",
    "Run FFC (Flat Field Correction)",
    "Sector Erase (4KB)",
    "Set AGC Damping Factor",
    "Set AGC Enable State",
    "Set AGC Histogram Statistics",
    "Set AGC Policy",
    "Set AGC ROI",
    "Set GPIO Mode",
    "Set GPIOA to 0xAA",
    "Set GPIOB to 0x55",
    "Set IODIRA to 0xFF (all inputs)",
    "Set IODIRB to 0x00 (all outputs)",
    "Set Operation Mode",
    "Set format to JPEG",
    "Set format to RGB565",
    "Set format to YUV422",
    "Set resolution to QQVGA",
    "Set resolution to QVGA",
    "Set resolution to VGA",
    "Start image capture",
    "Write 0x01 to register 0xFF",
    "Write Disable",
    "Write Enable",
    "Write Status Register-1",
    "Write Status Register-2",
    "Write Status Register-3",
};
