const char* meanings[] = {
    "Abort",
    "Acknowledgement",
    "Adaptive Cruise Control",
    "Address Claimed",
    "Address Claimed by Another Device",
    "Address Delete",
    "Address Requested",
    "Aftertreatment 1 Diesel Exhaust Fluid Tank 1 Control",
    "Aftertreatment 1 Diesel Exhaust Fluid Tank 1 Information",
    "Aftertreatment 1 Diesel Exhaust Fluid Tank 2 Control",
    "Aftertreatment 1 Diesel Exhaust Fluid Tank 2 Information",
    "Aftertreatment 1 Diesel Exhaust Fluid Tank 3 Information",
    "Aftertreatment 1 Diesel Exhaust Fluid Tank 4 Information",
    "Aftertreatment 1 Diesel Particulate Filter",
    "Aftertreatment 1 Diesel Particulate Filter Control",
    "Aftertreatment 1 Diesel Particulate Filter History",
    "Aftertreatment 1 Diesel Particulate Filter Regeneration",
    "Aftertreatment 1 Gas Intake",
    "Aftertreatment 1 Gas Outlet",
    "Aftertreatment 1 Gas Particulate Filter",
    "Aftertreatment 1 Gas Particulate Filter Control",
    "Aftertreatment 1 Gas Particulate Filter History",
    "Aftertreatment 1 Gas Particulate Filter Regeneration",
    "Aftertreatment 1 SCR Information",
    "Aftertreatment 2 Diesel Exhaust Fluid Tank 1 Control",
    "Aftertreatment 2 Diesel Exhaust Fluid Tank 1 Information",
    "Aftertreatment 2 Diesel Exhaust Fluid Tank 2 Control",
    "Aftertreatment 2 Diesel Exhaust Fluid Tank 2 Information",
    "Aftertreatment 2 Diesel Exhaust Fluid Tank 3 Information",
    "Aftertreatment 2 Diesel Exhaust Fluid Tank 4 Information",
    "Aftertreatment 2 Diesel Particulate Filter",
    "Aftertreatment 2 Diesel Particulate Filter Control",
    "Aftertreatment 2 Diesel Particulate Filter History",
    "Aftertreatment 2 Diesel Particulate Filter Regeneration",
    "Aftertreatment 2 Gas Intake",
    "Aftertreatment 2 Gas Outlet",
    "Aftertreatment 2 Gas Particulate Filter",
    "Aftertreatment 2 Gas Particulate Filter Control",
    "Aftertreatment 2 Gas Particulate Filter History",
    "Aftertreatment 2 Gas Particulate Filter Regeneration",
    "Aftertreatment 2 SCR Information",
    "Ambient Conditions",
    "Auxiliary Valve Command",
    "Auxiliary Valve Data",
    "BAM - Broadcast Announce Message",
    "CON - Connection Mode",
    "CTS - Clear to Send",
    "Cab Illumination",
    "Commanded Address",
    "DM1 - Active Diagnostic Trouble Codes",
    "DM11 - Clear All Active and Previously Active DTCs",
    "DM12 - Emissions-Related Active Diagnostic Trouble Codes",
    "DM13 - Stop/Start Broadcast",
    "DM14 - Memory Access Request",
    "DM15 - Memory Access Response",
    "DM16 - Binary Data Transfer",
    "DM17 - Diagnostic Readiness 2",
    "DM2 - Previously Active Diagnostic Trouble Codes",
    "DM3 - Diagnostic Data Clear/Reset",
    "DM4 - Freeze Frame Parameters",
    "DM5 - Diagnostic Readiness 1",
    "DM6 - Pending Diagnostic Trouble Codes",
    "DM7 - Commanded Diagnostic Test",
    "DM8 - Diagnostic Data Clear/Reset for Active DTCs",
    "DM9 - Diagnostic Data Clear/Reset for Previously Active DTCs",
    "ECU Identification",
    "ECU Performance",
    "EOM - End of Message",
    "Electronic Axle Controller 1",
    "Electronic Brake Controller 1",
    "Electronic Brake Controller 2",
    "Electronic Engine Controller 1",
    "Electronic Engine Controller 2",
    "Electronic Retarder Controller 1",
    "Electronic Tractor Controller",
    "Electronic Transmission Controller 1",
    "Electronic Transmission Controller 2",
    "Engine Air Intake Information",
    "Engine Calibration Information",
    "Engine Combustion Information",
    "Engine Configuration",
    "Engine Configuration 10",
    "Engine Configuration 11",
    "Engine Configuration 12",
    "Engine Configuration 13",
    "Engine Configuration 14",
    "Engine Configuration 15",
    "Engine Configuration 16",
    "Engine Configuration 17",
    "Engine Configuration 18",
    "Engine Configuration 19",
    "Engine Configuration 2",
    "Engine Configuration 20",
    "Engine Configuration 3",
    "Engine Configuration 4",
    "Engine Configuration 5",
    "Engine Configuration 6",
    "Engine Configuration 7",
    "Engine Configuration 8",
    "Engine Configuration 9",
    "Engine Coolant Information",
    "Engine Diagnostic Information",
    "Engine Emission Control Information",
    "Engine Exhaust Information",
    "Engine Fluid Level/Pressure",
    "Engine Fuel Delivery Pressure",
    "Engine Hours/Revolutions",
    "Engine Load Information",
    "Engine Maintenance Information",
    "Engine Oil Information",
    "Engine Performance Information",
    "Engine Power Information",
    "Engine Protection System",
    "Engine Protection System Configuration",
    "Engine Protection System Configuration 2",
    "Engine Protection System History",
    "Engine Protection System History 2",
    "Engine Protection System Status",
    "Engine Protection System Status 2",
    "Engine Protection System Timer",
    "Engine Speed History",
    "Engine Timing Information",
    "Engine Torque History",
    "Exhaust Gas Recirculation",
    "Fan Drive",
    "Fuel Consumption",
    "Fuel Economy",
    "Ground-Based Speed Sensor",
    "Hitch Control Command",
    "Hitch Control Data",
    "Hydraulic Pressure Controller",
    "Idle Operation",
    "Implement Controller",
    "Inlet/Exhaust Conditions",
    "Lighting Command",
    "Lighting Data",
    "PTO Control Command",
    "PTO Control Data",
    "Proprietary A",
    "Proprietary B",
    "RTS - Request to Send",
    "Request 2 PGN",
    "Request PGN",
    "Request for PGN",
    "Response to Request PGN",
    "Service Component Alarms",
    "Service Component Calibration",
    "Service Component Configuration",
    "Service Component Diagnostics",
    "Service Component Events",
    "Service Component Faults",
    "Service Component History",
    "Service Component Identification",
    "Service Component Logs",
    "Service Component Maintenance",
    "Service Component Operation",
    "Service Component Performance",
    "Service Component Status",
    "Service Component Warnings",
    "Service Distance Information",
    "Service Time Information",
    "Shutdown",
    "Software Identification",
    "Steering Controller",
    "Time/Date",
    "Total Engine Hours",
    "Total Engine Revolutions",
    "Total Fuel Used",
    "Total Idle Fuel Used",
    "Total Idle Hours",
    "Total Vehicle Distance",
    "Transfer PGN",
    "Transfer Protocol - Connection Abort",
    "Transport Protocol - Connection Management",
    "Transport Protocol - Data Transfer",
    "Trip Aftertreatment Information",
    "Trip Alternative Fuel Information",
    "Trip Axle Information",
    "Trip Battery Information",
    "Trip Brake Information",
    "Trip Cruise Control Information",
    "Trip Diagnostic Information",
    "Trip Distance",
    "Trip Distance on Alternative Fuel",
    "Trip Distance on Battery",
    "Trip Distance on Natural Gas",
    "Trip Driver Information",
    "Trip Electrical Information",
    "Trip Engine Hours",
    "Trip Engine Information",
    "Trip Environmental Information",
    "Trip Fan Information",
    "Trip Fuel Economy",
    "Trip Fuel Information",
    "Trip Fuel Used",
    "Trip Fuel Used on Alternative Fuel",
    "Trip Fuel Used on Battery",
    "Trip Fuel Used on Natural Gas",
    "Trip Idle Fuel Used",
    "Trip Idle Time",
    "Trip Information",
    "Trip Natural Gas Information",
    "Trip PTO Time",
    "Trip Steering Information",
    "Trip Suspension Information",
    "Trip Time",
    "Trip Time on Alternative Fuel",
    "Trip Time on Battery",
    "Trip Time on Natural Gas",
    "Trip Transmission Information",
    "Trip Vehicle Information",
    "Turbocharger",
    "Vehicle Direction and Speed",
    "Vehicle Distance",
    "Vehicle Dynamics",
    "Vehicle Electrical Power",
    "Vehicle Hours",
    "Vehicle Identification",
    "Vehicle Network Access",
    "Vehicle Network Adaptability",
    "Vehicle Network Alarms",
    "Vehicle Network Analysis",
    "Vehicle Network Availability",
    "Vehicle Network Compatibility",
    "Vehicle Network Configuration",
    "Vehicle Network Control",
    "Vehicle Network Diagnostics",
    "Vehicle Network Events",
    "Vehicle Network Faults",
    "Vehicle Network Flexibility",
    "Vehicle Network Information",
    "Vehicle Network Integration",
    "Vehicle Network Logs",
    "Vehicle Network Maintenance",
    "Vehicle Network Monitoring",
    "Vehicle Network Operation",
    "Vehicle Network Optimization",
    "Vehicle Network Performance",
    "Vehicle Network Reliability",
    "Vehicle Network Reporting",
    "Vehicle Network Scalability",
    "Vehicle Network Security",
    "Vehicle Network Status",
    "Vehicle Network Warnings",
    "Vehicle Position",
    "Vehicle Speed",
    "Vehicle Weight",
    "Virtual Terminal",
};
