const char* meanings_function[] = {
    "combined read and write",
    "diagnostics",
    "encapsulated interface transport",
    "get communication event counter",
    "get communication event log",
    "get device identification",
    "get device-specific status",
    "modify bits in a register",
    "read analog inputs",
    "read analog outputs",
    "read digital inputs",
    "read digital outputs",
    "read from a FIFO queue",
    "read from file records",
    "set a single analog output",
    "set a single digital output",
    "set multiple analog outputs",
    "set multiple digital outputs",
    "write to file records",
};
